baseURL = 'https://haihuynh226.github.io/'
languageCode = 'en-us'
title = 'MangoAds Site'
theme = 'BlogRa'
canonifyURLs=true
pluralizeListTitles = false
summaryLength   = 25
[params]
description     = "The Ultimate Tech Blogging Theme"
contactEmail    = "your-email@domain.com"
footer          = ""
googleSearch    = "google-cse-key"
googleAnalytics = "G-A1B2C3D4E5" # v4
adsense         = "adsense-key"
math            = false   # best to enable this in the front matter of a page
mermaid         = false   # best to enable this in the front matter of a page

# Social Media Params
facebook   = "https://www.facebook.com/DevHacker-2351204168278028"
twitter    = ""
youtube    = "https://www.youtube.com/channel/UC6uDg4IlPbLh2xNKrqnBczw"
instagram  = ""
github     = "https://github.com/rafed"
pinterest  = ""
linkedin   = "https://www.linkedin.com/in/rafed-m-yasir/"

# Configure the site menu here
[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Posts"
        url = "/posts/"
        weight = 2

    [[menu.main]]
        identifier = "blog"
        name = "Blog"
        weight = 3
        [[menu.main]]
            parent = "blog"
            name = "Sections"
            url = "/sections/"
            weight = 1
        [[menu.main]]
            parent = "blog"
            name = "divider"
            weight = 2
        [[menu.main]]
            parent = "blog"
            name = "Tags"
            url = "/tags/"
            weight = 3
    [[menu.main]]
        name = "About"
        url = "/about/"
        weight = 4

    [[menu.main]]
        name = "Contact"
        url = "/contact/"
        weight = 5

# Don't touch this
[markup.goldmark.renderer]
    unsafe = true